//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemploDBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livros
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Autor { get; set; }
        public string Editora { get; set; }
        public int BibliotecaId { get; set; }
        public Nullable<int> NumeroPaginas { get; set; }
    
        public virtual Biblioteca Biblioteca { get; set; }
    }
}
